### ISSUE TITLE
Crash when displaying map

### ISSUE THREAD

**Issue by opk12** [fvasco/pinpoi#40]
(edited) I get this whenever I try to open the builtin map on a GPX of 1500 points. The map shows up in the background while loading, but the loading never finishes, then the app crashes.

With another smaller category, the map shows and the app does not crash.

```
FATAL EXCEPTION: main
Process: io.github.fvasco.pinpoi, PID: 2884
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@acde074 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:922)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:105)
	at android.widget.Toast$TN.handleShow(Toast.java:746)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:622)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

Version 1.10.4 on Samsung Android 7.1.

**Comment by fvasco** [comment]
Hi @opk12,
thank you for this issue.

I just released the version 89 (1.10.6) , it will be deployed soon.
Please try the new version and keep update this issue.
